<a href="https://colab.research.google.com/github/0xFAB10/Data-Analysis-Exercises/blob/main/Binery_Study_Bank_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import altair as alt

In [2]:
file_url = 'https://raw.githubusercontent.com/'\
           'PacktWorkshops/The-Data-Science-Workshop/'\
           'master/Chapter03/bank-full.csv'
bankData = pd.read_csv(file_url, sep=";")
bankData.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [3]:
filter_mask = bankData['y'] == 'yes'
bankSub1 = bankData[filter_mask].groupby('age')['y'].agg(count='count').reset_index()
bankSub1

    age  count
0    18      7
1    19     11
2    20     15
3    21     22
4    22     40
..  ...    ...
69   87      3
70   90      2
71   92      2
72   93      2
73   95      1

[74 rows x 2 columns]

In [4]:
help(pd.DataFrame.agg)

Help on function aggregate in module pandas.core.frame:

aggregate(self, func=None, axis: 'Axis' = 0, *args, **kwargs)
    Aggregate using one or more operations over the specified axis.

    Parameters
    ----------
    func : function, str, list or dict
        Function to use for aggregating the data. If a function, must either
        work when passed a DataFrame or when passed to DataFrame.apply.

        Accepted combinations are:

        - function
        - string function name
        - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
        - dict of axis labels -> functions, function names or list of such.
    axis : {0 or 'index', 1 or 'columns'}, default 0
            If 0 or 'index': apply function to each column.
            If 1 or 'columns': apply function to each row.
    *args
        Positional arguments to pass to `func`.
    **kwargs
        Keyword arguments to pass to `func`.

    Returns
    -------
    scalar, Series or DataFrame

        The return can be:

        * scalar : when Series.agg is called with single function
        * Series : when DataFrame.agg is called with a single function
        * DataFrame : when DataFrame.agg is called with several functions

        Return scalar, Series or DataFrame.

    The aggregation operations are always performed over an axis, either the
    index (default) or the column axis. This behavior is different from
    `numpy` aggregation functions (`mean`, `median`, `prod`, `sum`, `std`,
    `var`), where the default is to compute the aggregation of the flattened
    array, e.g., ``numpy.mean(arr_2d)`` as opposed to
    ``numpy.mean(arr_2d, axis=0)``.

    `agg` is an alias for `aggregate`. Use the alias.

    See Also
    --------
    DataFrame.apply : Perform any type of operations.
    DataFrame.transform : Perform transformation type operations.
    core.groupby.GroupBy : Perform operations over groups.
    core.resample.Resampler : Perform operations over resampled bins.
    core.window.Rolling : Perform operations over rolling window.
    core.window.Expanding : Perform operations over expanding window.
    core.window.ExponentialMovingWindow : Perform operation over exponential weighted
        window.

    Notes
    -----
    `agg` is an alias for `aggregate`. Use the alias.

    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    A passed user-defined-function will be passed a Series for evaluation.

    Examples
    --------
    >>> df = pd.DataFrame([[1, 2, 3],
    ...                    [4, 5, 6],
    ...                    [7, 8, 9],
    ...                    [np.nan, np.nan, np.nan]],
    ...                   columns=['A', 'B', 'C'])

    Aggregate these functions over the rows.

    >>> df.agg(['sum', 'min'])
            A     B     C
    sum  12.0  15.0  18.0
    min   1.0   2.0   3.0

    Different aggregations per column.

    >>> df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})
            A    B
    sum  12.0  NaN
    min   1.0  2.0
    max   NaN  8.0

    Aggregate different functions over the columns and rename the index of the resulting
    DataFrame.

    >>> df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))
         A    B    C
    x  7.0  NaN  NaN
    y  NaN  2.0  NaN
    z  NaN  NaN  6.0

    Aggregate over the columns.

    >>> df.agg("mean", axis="columns")
    0    2.0
    1    5.0
    2    8.0
    3    NaN
    dtype: float64

In [5]:
# Visualising the relationship using altair
alt.Chart(bankSub1).mark_line().encode(x='age', y='agegrp')

ValueError: ignored

alt.Chart(...)

In [6]:
# Getting another perspective
ageTot = bankData.groupby('age')['y']\
         .agg(ageTot='count').reset_index()
ageTot.head()

   age  ageTot
0   18      12
1   19      35
2   20      50
3   21      79
4   22     129

In [7]:
# Getting all the details in one place
ageProp = bankData.groupby(['age','y'])['y']\
          .agg(ageCat='count').reset_index()
ageProp.head()

   age    y  ageCat
0   18   no       5
1   18  yes       7
2   19   no      24
3   19  yes      11
4   20   no      35

In [8]:
# Merging both the data frames
ageComb = pd.merge(ageProp, ageTot,left_on = ['age'], \
                   right_on = ['age'])
ageComb['catProp'] = (ageComb.ageCat/ageComb.ageTot)*100
ageComb.head()

   age    y  ageCat  ageTot    catProp
0   18   no       5      12  41.666667
1   18  yes       7      12  58.333333
2   19   no      24      35  68.571429
3   19  yes      11      35  31.428571
4   20   no      35      50  70.000000

In [9]:
# Visualising the relationship using altair
alt.Chart(ageComb).mark_line()\
   .encode(x='age', y='catProp').facet(column='y')

alt.FacetChart(...)